version: '3.3'
services:

  # TPM trusted third party (RAT repository)
  ttp:
    image: fraunhoferaisec/ttpsim:example
    container_name: trusted-3rd-p
    build:
      context: '../../rat-repository'
    ports:
      - "31337:31337"
    networks:
      - webnet

networks:
  webnet:
    external: true
